# Generated by Django 4.1.1 on 2022-10-11 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0004_alter_profile_type_work'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='TypeWork',
        ),
    ]
